# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  jobs:
  - job: Windows
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: TARGET="x86_64-pc-windows-gnu" bash ./ci/publish.sh
  - job: Linux Armhf
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: TARGET="armv7-unknown-linux-musleabihf" bash ./ci/publish.sh
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: TARGET="x86_64-unknown-linux-musl" bash ./ci/publish.sh
  - job: Linux Arm64
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: TARGET="aarch64-unknown-linux-gnu" bash ./ci/publish.sh
  - job: Darwin
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - script: TARGET="x86_64-apple-darwin" bash ./ci/publish.sh

- task: GitHubRelease@0
  displayName: Create Github Release
  inputs:
    gitHubConnection: release
    repositoryName: '$(Build.Repository.Name)' 
    action: 'edit'
    target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
    tagSource: 'auto' 
